
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mete
 */
public class Wordle extends javax.swing.JFrame {

    String kelime = "ARABA";
    char[] kelimeKarakter = kelime.toCharArray();

    /**
     * Creates new form Wordle
     */
    public Wordle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf00 = new javax.swing.JTextField();
        tf01 = new javax.swing.JTextField();
        tf02 = new javax.swing.JTextField();
        tf03 = new javax.swing.JTextField();
        tf04 = new javax.swing.JTextField();
        onaylaBtn = new javax.swing.JButton();
        tf10 = new javax.swing.JTextField();
        tf11 = new javax.swing.JTextField();
        tf12 = new javax.swing.JTextField();
        tf13 = new javax.swing.JTextField();
        tf14 = new javax.swing.JTextField();
        tf20 = new javax.swing.JTextField();
        tf21 = new javax.swing.JTextField();
        tf22 = new javax.swing.JTextField();
        tf23 = new javax.swing.JTextField();
        tf24 = new javax.swing.JTextField();
        tf30 = new javax.swing.JTextField();
        tf31 = new javax.swing.JTextField();
        tf32 = new javax.swing.JTextField();
        tf33 = new javax.swing.JTextField();
        tf34 = new javax.swing.JTextField();
        tf40 = new javax.swing.JTextField();
        tf41 = new javax.swing.JTextField();
        tf42 = new javax.swing.JTextField();
        tf43 = new javax.swing.JTextField();
        tf44 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf41KeyTyped(evt);
            }
        });

        tf00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf00KeyTyped(evt);
            }
        });

        tf01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf01KeyTyped(evt);
            }
        });

        tf02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf02KeyTyped(evt);
            }
        });

        tf03.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf03KeyTyped(evt);
            }
        });

        tf04.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf04KeyTyped(evt);
            }
        });

        onaylaBtn.setText("Onayla");
        onaylaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaBtnActionPerformed(evt);
            }
        });

        tf10.setEditable(false);
        tf10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf10KeyTyped(evt);
            }
        });

        tf11.setEditable(false);
        tf11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf11KeyTyped(evt);
            }
        });

        tf12.setEditable(false);
        tf12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf12KeyTyped(evt);
            }
        });

        tf13.setEditable(false);
        tf13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf13KeyTyped(evt);
            }
        });

        tf14.setEditable(false);
        tf14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf14KeyTyped(evt);
            }
        });

        tf20.setEditable(false);
        tf20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf20KeyTyped(evt);
            }
        });

        tf21.setEditable(false);
        tf21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf21KeyTyped(evt);
            }
        });

        tf22.setEditable(false);
        tf22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf22KeyTyped(evt);
            }
        });

        tf23.setEditable(false);
        tf23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf23KeyTyped(evt);
            }
        });

        tf24.setEditable(false);
        tf24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf24KeyTyped(evt);
            }
        });

        tf30.setEditable(false);
        tf30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf30KeyTyped(evt);
            }
        });

        tf31.setEditable(false);
        tf31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf31KeyTyped(evt);
            }
        });

        tf32.setEditable(false);
        tf32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf32KeyTyped(evt);
            }
        });

        tf33.setEditable(false);
        tf33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf33KeyTyped(evt);
            }
        });

        tf34.setEditable(false);
        tf34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf34KeyTyped(evt);
            }
        });

        tf40.setEditable(false);
        tf40.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf40KeyTyped(evt);
            }
        });

        tf41.setEditable(false);
        tf41.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf41KeyTyped(evt);
            }
        });

        tf42.setEditable(false);
        tf42.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf42KeyTyped(evt);
            }
        });

        tf43.setEditable(false);
        tf43.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf43KeyTyped(evt);
            }
        });

        tf44.setEditable(false);
        tf44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf44KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf00, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf01, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf02, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf03, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf04, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf30, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf31, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf32, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf34, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(onaylaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf40, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf41, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf42, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf43, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf44, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf04, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(onaylaBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void tf00KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf00KeyTyped
        karakterSiniriVeBuyukHarf(tf00, evt);
    }//GEN-LAST:event_tf00KeyTyped

    private void tf01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf01KeyTyped
        karakterSiniriVeBuyukHarf(tf01, evt);
    }//GEN-LAST:event_tf01KeyTyped

    private void tf02KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf02KeyTyped
        karakterSiniriVeBuyukHarf(tf02, evt);
    }//GEN-LAST:event_tf02KeyTyped

    private void tf03KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf03KeyTyped
        karakterSiniriVeBuyukHarf(tf03, evt);
    }//GEN-LAST:event_tf03KeyTyped

    private void tf04KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf04KeyTyped
        karakterSiniriVeBuyukHarf(tf04, evt);
    }//GEN-LAST:event_tf04KeyTyped

    private void onaylaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaylaBtnActionPerformed

 
        JTextField[] birinciSatirDizi = {tf00, tf01, tf02, tf03, tf04};
        JTextField[] ikinciSatirDizi = {tf10, tf11, tf12, tf13, tf14};
        JTextField[] ucuncuSatirDizi = {tf20, tf21, tf22, tf23, tf24};
        JTextField[] dorduncuSatirDizi = {tf30, tf31, tf32, tf33, tf34};
        JTextField[] besinciSatirDizi = {tf40, tf41, tf42, tf43, tf44};
        String arabaTrueMu = "";

        if (tf00.getText() != "") {
            dogrulukKontrol(birinciSatirDizi);
            for (int i = 0; i < 5; i++) {
                arabaTrueMu += birinciSatirDizi[i].getText();
            }
            if (arabaTrueMu.equals("ARABA")) {
                JOptionPane.showMessageDialog(null, "Doğru Kelime!");
                System.exit(0);
            }
            for (int i = 0; i < 5; i++) {
                ikinciSatirDizi[i].setEditable(true);
            }
            
        }
        if (tf10.getText() != "") {
            dogrulukKontrol(ikinciSatirDizi);
            for (int i = 0; i < 5; i++) {
                arabaTrueMu = "";
                arabaTrueMu += ikinciSatirDizi[i].getText();
            }
            if (arabaTrueMu.equals("ARABA")) {

                JOptionPane.showMessageDialog(null, "Doğru Kelime!");
                System.exit(0);
            }
            for (int i = 0; i < 5; i++) {
                ucuncuSatirDizi[i].setEditable(true);
            }

        }
        if (tf20.getText() != "") {
            dogrulukKontrol(ucuncuSatirDizi);
            for (int i = 0; i < 5; i++) {
                arabaTrueMu = "";
                arabaTrueMu += ucuncuSatirDizi[i].getText();
            }
            if (arabaTrueMu.equals("ARABA")) {
                JOptionPane.showMessageDialog(null, "Doğru Kelime!");
                System.exit(0);
            }
            for (int i = 0; i < 5; i++) {
                dorduncuSatirDizi[i].setEditable(true);
            }

        }
        if (tf30.getText() != "") {
            dogrulukKontrol(dorduncuSatirDizi);
            for (int i = 0; i < 5; i++) {
                arabaTrueMu = "";
                arabaTrueMu += dorduncuSatirDizi[i].getText();
            }
            if (arabaTrueMu.equals("ARABA")) {
                JOptionPane.showMessageDialog(null, "Doğru Kelime!");
                System.exit(0);
            }
            for (int i = 0; i < 5; i++) {
                besinciSatirDizi[i].setEditable(true);
            }

        }
        if (tf40.getText() != "") {

            dogrulukKontrol(besinciSatirDizi);
            for (int i = 0; i < 5; i++) {
                arabaTrueMu = "";
                arabaTrueMu += ikinciSatirDizi[i].getText();
            }
            if (arabaTrueMu.equals("ARABA")) {
                JOptionPane.showMessageDialog(null, "Doğru Kelime!");
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(null, "Bilemediniz!");
                System.exit(0);
            }
        }


    }//GEN-LAST:event_onaylaBtnActionPerformed

    private void tf10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf10KeyTyped
        karakterSiniriVeBuyukHarf(tf10, evt);
    }//GEN-LAST:event_tf10KeyTyped

    private void tf11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf11KeyTyped
        karakterSiniriVeBuyukHarf(tf11, evt);
    }//GEN-LAST:event_tf11KeyTyped

    private void tf12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf12KeyTyped
        karakterSiniriVeBuyukHarf(tf12, evt);
    }//GEN-LAST:event_tf12KeyTyped

    private void tf13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf13KeyTyped
        karakterSiniriVeBuyukHarf(tf13, evt);
    }//GEN-LAST:event_tf13KeyTyped

    private void tf14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf14KeyTyped
        karakterSiniriVeBuyukHarf(tf14, evt);
    }//GEN-LAST:event_tf14KeyTyped

    private void tf20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf20KeyTyped
        karakterSiniriVeBuyukHarf(tf20, evt);
    }//GEN-LAST:event_tf20KeyTyped

    private void tf21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf21KeyTyped
        karakterSiniriVeBuyukHarf(tf21, evt);
    }//GEN-LAST:event_tf21KeyTyped

    private void tf22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf22KeyTyped
        karakterSiniriVeBuyukHarf(tf22, evt);
    }//GEN-LAST:event_tf22KeyTyped

    private void tf23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf23KeyTyped
        karakterSiniriVeBuyukHarf(tf23, evt);
    }//GEN-LAST:event_tf23KeyTyped

    private void tf24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf24KeyTyped
        karakterSiniriVeBuyukHarf(tf24, evt);
    }//GEN-LAST:event_tf24KeyTyped

    private void tf30KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf30KeyTyped
        karakterSiniriVeBuyukHarf(tf30, evt);
    }//GEN-LAST:event_tf30KeyTyped

    private void tf31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf31KeyTyped
        karakterSiniriVeBuyukHarf(tf31, evt);
    }//GEN-LAST:event_tf31KeyTyped

    private void tf32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf32KeyTyped
        karakterSiniriVeBuyukHarf(tf32, evt);
    }//GEN-LAST:event_tf32KeyTyped

    private void tf33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf33KeyTyped
        karakterSiniriVeBuyukHarf(tf33, evt);
    }//GEN-LAST:event_tf33KeyTyped

    private void tf34KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf34KeyTyped
        karakterSiniriVeBuyukHarf(tf34, evt);
    }//GEN-LAST:event_tf34KeyTyped

    private void tf40KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf40KeyTyped
        karakterSiniriVeBuyukHarf(tf40, evt);
    }//GEN-LAST:event_tf40KeyTyped

    private void tf41KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf41KeyTyped
        karakterSiniriVeBuyukHarf(tf41, evt);
    }//GEN-LAST:event_tf41KeyTyped

    private void tf42KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf42KeyTyped
        karakterSiniriVeBuyukHarf(tf42, evt);
    }//GEN-LAST:event_tf42KeyTyped

    private void tf43KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf43KeyTyped
        karakterSiniriVeBuyukHarf(tf43, evt);
    }//GEN-LAST:event_tf43KeyTyped

    private void tf44KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf44KeyTyped
        karakterSiniriVeBuyukHarf(tf44, evt);
    }//GEN-LAST:event_tf44KeyTyped

    public void karakterSiniriVeBuyukHarf(JTextField tf, java.awt.event.KeyEvent evt) {
        boolean max = tf.getText().length() > 0;
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
        if (max) {
            evt.consume();
        }
    }

    public void dogrulukKontrol(JTextField[] tf) {

        for (int i = 0; i < 5; i++) {
            if (kelime.indexOf(tf[i].getText()) != -1) {
                char[] diziKelime = tf[i].getText().toCharArray();
                if (kelimeKarakter[i] == diziKelime[0]) {
                    tf[i].setBackground(Color.green);
                    tf[i].setEditable(false);
                } else {
                    tf[i].setBackground(Color.yellow);
                    tf[i].setEditable(false);
                }

            } else {
                tf[i].setBackground(Color.red);
                tf[i].setEditable(false);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wordle().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton onaylaBtn;
    private javax.swing.JTextField tf00;
    private javax.swing.JTextField tf01;
    private javax.swing.JTextField tf02;
    private javax.swing.JTextField tf03;
    private javax.swing.JTextField tf04;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf13;
    private javax.swing.JTextField tf14;
    private javax.swing.JTextField tf20;
    private javax.swing.JTextField tf21;
    private javax.swing.JTextField tf22;
    private javax.swing.JTextField tf23;
    private javax.swing.JTextField tf24;
    private javax.swing.JTextField tf30;
    private javax.swing.JTextField tf31;
    private javax.swing.JTextField tf32;
    private javax.swing.JTextField tf33;
    private javax.swing.JTextField tf34;
    private javax.swing.JTextField tf40;
    private javax.swing.JTextField tf41;
    private javax.swing.JTextField tf42;
    private javax.swing.JTextField tf43;
    private javax.swing.JTextField tf44;
    // End of variables declaration//GEN-END:variables
}
